name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Sonar Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: cmd
        run: |
          sonar-scanner ^
            -Dsonar.projectKey=python-advanced-demo ^
            -Dsonar.sources=sonar-python-advanced/src,bad_practices.py ^
            -Dsonar.tests=sonar-python-advanced/test ^
            -Dsonar.host.url=http://localhost:9000 ^
            -Dsonar.token=%SONAR_TOKEN%